language: elixir
elixir:
    - 1.4.5
    - 1.5.1
otp_release:
    - 19.3
    - 20.0

sudo: required
services:
  - docker

branches:
  only:
    - master
    - stable
    - /^rel\-\d+\.\d+$/
    - /^\d+\.\d+\.\d+([a-z0-9\-\+])*/

cache:
  directories:
      - .dialyzer

before_script:
  - tools/travis-setup.sh

env:
    - PRESET=exunit MIX_ENV=test
    - PRESET=dialyzer MIX=test

script: tools/travis-test.sh

after_success:
  - tools/travis-docker.sh
