language: elixir

sudo: required
services:
  - docker

branches:
  only:
    - master
    - stable
    - /^rel\-\d+\.\d+$/
    - /^\d+\.\d+\.\d+([a-z0-9\-\+])*/

cache:
  directories:
      - .dialyzer

before_script:
  - tools/travis-setup.sh

elixir:
    - 1.5
    - 1.6
otp_release:
    - 19.3
    - 20.3.2
env:
    - PRESET=exunit MIX_ENV=test

script: tools/travis-test.sh

matrix:
    include:
        - stage: test
          otp_release: 20.3.2
          env: PRESET=dialyzer MIX_ENV=test
        - stage: deploy
          elixir: 1.6
          otp_release: 20.3.2
          script: tools/travis-docker.sh
